name: lynight
description: application pour le projet E3 Esiee Paris

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  sliding_up_panel: ^0.3.4
  url_launcher: ^5.0.3
  #geoflutterfire : ^2.0.2
  location: ^2.3.5
  google_maps_flutter: ^0.5.21+8
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.0.6
  image_picker: 0.6.1+8
  flutter_datetime_picker: ^1.2.1
  font_awesome_flutter: ^8.5.0
  qr_flutter: ^2.0.0
  image: ^2.1.4
  percent_indicator: ^2.1.1
  flutter_slidable: ^0.5.4
  intl: ^0.16.0
  path_provider: ^1.3.1
  pull_to_refresh: ^1.5.7
  transparent_image: ^1.0.0
  flare_flutter: ^1.8.1
  provider: ^3.1.0+1
  braintree_payment: ^1.2.2
  firebase_messaging: ^6.0.9
  algolia: ^0.1.6+1
  firebase_in_app_messaging: ^0.1.1+1
  google_sign_in: ^4.1.4




  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  carousel_pro: ^0.0.1

  cupertino_icons: ^0.1.2
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/boite.jpg
    - assets/nightClub.jpg
    - assets/festival.jpg
    - assets/bloon_pin.png
    - assets/pin.png
    - assets/bloon_final_pin.png
    - assets/bloonLogo.png
    - assets/gris_chargement.jpg
    - assets/splash_screen_bloon.flr
    - assets/google_logo.png
    - icons/
    #- assets/loupe.png
    #- assets/test.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Montserrat
        fonts:
          - asset: fonts/Montserrat/Montserrat-Regular.ttf

      - family: Comfortaa
        fonts:
          - asset: fonts/Comfortaa/Comfortaa[wght].ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic


          #- asset: packages/my_package/fonts/Raleway-Medium.ttf
            # weight: 500
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
